services:
  - type: web
    name: application-form
    env: php
    buildCommand: php artisan config:clear && composer install --no-dev --optimize-autoloader
    startCommand: php artisan migrate --force && heroku-php-apache2 public/
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_URL
        value: ${RENDER_EXTERNAL_URL}
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: application-db
          property: connectionString

databases:
  - name: application-db
    databaseName: application_form
    user: laravel
